config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  devise_for :users, :skip => [:registrations]

  as :user do
    get '/users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put '/users' => 'devise/registrations#update', :as => 'user_registration'
  end

  devise_for :patients, :skip => [:registrations], controllers: { sessions: 'patients/sessions' }

  as :patient do
    get "/patients/edit" => "devise/registrations#edit", :as => :edit_patient_registration
    put "/patients" => "devise/registrations#update", :as => :patient_registration
  end

  root to: 'dashboard#index'

  resources :dashboard, only: [:index] do
    collection do
      get 'states'
      post 'transaction_callback'
    end
  end

  resources :patients, except: :destroy do
    collection do
      post :send_otp
    end
    resources :consultations do
      resources :histories, only: [:create, :update]
      resources :treatments, only: [:create, :update]
      resources :examinations
      resources :diagnoses
      resources :general_notes
      resources :laboratory_requests, except:  :index
      resources :laboratory_results
      member do
        patch 'update_provider'
        patch 'update_disease'
      end
    end
  end

  resources :users, only: [] do
    collection do
      get 'user_balance'
      post 'add_tokens'
    end
    member do
      post 'send_reset_password_token'
    end
  end

  resources :clinics, only: [:index, :show] do
    member do
      get 'outcomes'
    end
    resources :transactions, only: [:create]
  end
  resources :transactions, only: [:index]

  get '/laboratory_patients', to: 'laboratory_requests#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :healthcare_professionals, except: [:show, :destroy]

  get '*path' => redirect('/')
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_all_clinics, only: [:index, :show]

  def index
    gon.contract_abi = ContractSetting[:contractABI]
    gon.contract_addresss = ContractSetting[:contractAddress]
  end

  def show
    @clinic = @clinics.find_by_id(params[:id])
    @transaction = @clinic.transactions.new
    @transaction_count = current_user.distribution_overviews.where.not(status: DistributionOverview::STATUS[:completed]).count
    gon.contract_abi = ContractSetting[:contractABI]
    gon.contract_addresss = ContractSetting[:contractAddress]
  end

  def outcomes
    transactions = current_user.transactions.where(clinic_id: params[:id], status: Transaction::STATUS[:completed])
    p_ids = transactions.collect(&:patients_ids)
    @transaction_data = {}
    @transaction_data[:patients] = transactions.sum(:number_of_patients)
    @transaction_data[:tokens] = transactions.sum(:number_of_tokens).to_i
    @patients = Patient.where(id: p_ids.flatten.uniq).includes(:consultations).page(params[:page]).per(20)
    redirect_to clinic_path(params[:id]) unless @patients.present?
  end

  private

  def find_all_clinics
    @clinics = User.with_role(Role::NAMES[:clinic])
  end
end

app/helpers/clinics_helper.rb
module ClinicsHelper
  def available_patients clinic
    clinic.all_patients.count - total_patient(clinic)
  end

  def patients_outcomes_status(clinic, status)
    current_user.transactions.where(clinic_id: clinic.id, status: status).map { |t| t.patients_ids }.flatten.count
  end

  def total_patient clinic
    current_user.transactions.where(clinic_id: clinic.id).map { |t| t.patients_ids }.flatten.count
  end
end

app/views/clinics/_confirm_purchase.html.erb
<div class="modal fade token_modal" id="token-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= simple_form_for(@transaction, method: :post, url: clinic_transactions_path(@clinic)) do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
          <h2>Enter the number of patients you'd like to assist</h2>
          <div class="form-group">
            <label>Number of Patients</label>
            <%= f.input :number_of_patients, label: false, input_html: { class: 'form-control', placeholder: "Enter number of patients", id: "patients-number",  min: 1 } %>
          </div>
          <div class="form-group">
            <label>Number of Tokens Required</label>
            <%= f.input :number_of_tokens, label: false, input_html: { class: 'form-control disabled', placeholder: "Enter number of tokens", id: "tokens-number", min: 0 } %>
          </div>
          <%= f.hidden_field :clinic_id, value: @clinic.id %>
          <%= f.hidden_field :tx_hash %>
        </div>
        <div class="modal-footer">
          <div class="purchase-btn">
            <%= f.submit "Confirm Purchase", class: "purchase-submit" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).on("turbolinks:load", function(){
    $("#patients-number").on('change', function(){
      let patient = parseInt($(this).val())
      $("#tokens-number").val(patient * 2);
    })
  })
</script>

app/views/clinics/index.html.erb
<div id="content">
  <%= render partial: '/shared/mobile_sidebar' %>

  <div class="heading">
    <h2>Choose from the following Projects / Charities</h2>
  </div>

  <div class="col-md-7 col-sm-12 col-xs-12 pad-none resp-pad">
    <div class="charity-block">
      <ul>
        <% @clinics.each do |clinic| %>
          <li>
            <%= link_to clinic_path(clinic) do %>
              <%= image_tag('charity-icon.png') %>
              <%= clinic.fullname %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div> <!-- charity Block -->
  </div>

</div>

app/views/clinics/outcomes.html.erb
<div id="content">
  <%= render partial: '/shared/mobile_sidebar' %>

  <div class="row row-margin">
    <div class="heading step-heading col-md-5 col-sm-5 col-xs-12">
      <h2>Patient Outcomes List</h2>
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12 text-right pull-right resp-pad">
      <div class="col-md-12 col-sm-12 col-xs-12 pad-none resp-pad">
        <div class="clinic-block">
          <div class="clinic-blk list-ul">
            <div class="inner-div">
              <a>
                <ul class="clinic-ul">
                  <li><%= image_tag('clinic-icon.png') %></li>
                  <li><span class="strong-text"><%= @transaction_data[:tokens] %></span> tokens</li>
                  <li class="border-right"></li>
                  <li><span class="strong-text"><%= @transaction_data[:patients] %></span> Patients</li>
                </ul>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="patient-list table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Patient ID</th>
          <th>Lab Results Delivered</th>
          <th>Medication Prescribed</th>
        </tr>
      </thead>
      <tbody>
        <% @patients.each do |patient| %>
          <tr>
            <td><%= patient.uid %></td>
            <td><%= patient.lab_result_available %></td>
            <td><%= patient.medication_prescribed %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= paginate @patients %>
</div>

app/views/clinics/show.html.erb
<div id="content">
  <%= render partial: '/shared/mobile_sidebar' %>

  <div class="alert alert-success transaction-toggle transaction-alert">
    Requested transaction for tokens is in progress...
  </div>
  <div class="alert alert-success p-transaction-toggle p-transaction-alert">
    Requested transaction for patients is in progress...
  </div>
  <div class="back-btn">
    <%= link_to clinics_path do %>
      <%= image_tag('back-icon.png') %>
      <span>BACK</span>
    <% end %>
    <div class="pull-right">Available Tokens : <span class="balance"></span> Tokens
      <div class="btn btn-primary add-tokens">Add Tokens</div>
    </div>
  </div>
  <div class="heading step-heading">
    <h3>
      <%= @clinic.fullname %>
      <span class="pull-right">Total Patients Available : <%= available_patients(@clinic) %></span>
    </h3>
    <p>Choose the number of patient records you can see</p>
  </div>

  <div class="col-md-7 col-sm-12 col-xs-12 pad-none resp-pad">
    <div class="clinic-block">
      <div class="clinic-blk">
        <div class="inner-div">
          <ul class="clinic-ul">
            <li class="pull-left">
              <span class="strong-text"><%= patients_outcomes_status(@clinic, "COMPLETED") %></span>
              Patients
            </li>
            <li class="outcome-btn pull-right">
              <% path = patients_outcomes_status(@clinic, "COMPLETED") > 0 ? outcomes_clinic_path(@clinic.id) : 'javascript:void(0)'%>
              <%= link_to "View Outcomes", path %>
            </li>
          </ul>
        </div>
        <div class="inner-div">
          <a href="javascript:void(0);" class="token-patients" data-tokens="10" data-patients="5">
            <ul class="clinic-ul">
              <li><%= image_tag('clinic-icon.png') %></li>
              <li><span class="strong-text">10</span> tokens</li>
              <li class="border-right"></li>
              <li><span class="strong-text">5</span> Patients</li>
            </ul>
          </a>
        </div>
        <div class="inner-div">
          <a href="javascript:void(0);" class="token-patients" data-tokens="20" data-patients="10">
            <ul class="clinic-ul">
              <li><%= image_tag('clinic-icon.png') %></li>
              <li><span class="strong-text">20</span> tokens</li>
              <li class="border-right"></li>
              <li><span class="strong-text">10</span> Patients</li>
            </ul>
          </a>
        </div>
        <div class="inner-div">
          <a href="javascript:void(0);" class="token-patients" data-tokens="50" data-patients="25">
            <ul class="clinic-ul">
              <li><%= image_tag('clinic-icon.png') %></li>
              <li><span class="strong-text">50</span> tokens</li>
              <li class="border-right"></li>
              <li><span class="strong-text">25</span> Patients</li>
            </ul>
          </a>
        </div>
      </div>
    </div> <!-- charity Block -->
    <div class="clearfix"></div>

    <div class="or-section">
      <div class="or">
        <span>OR</span>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="click-btn">
      <a href="javascript:void(0);" data-toggle="modal" data-target="#token-modal" data-tokens="" data-patients="">Click here to choose</a>
    </div>
  </div>
</div>
<%= render partial: 'confirm_purchase' %>
<script type="text/javascript">
  $(document).ready(function(){
    if(parseInt("<%= @transaction_count %>") > 0){
      $('.transaction-alert').removeClass('transaction-toggle');
    }

    if(parseInt("<%= patients_outcomes_status(@clinic, "PENDING") %>") > 0){
      $('.p-transaction-alert').removeClass('p-transaction-toggle');
    }

    function purchaseDialog(){
      BootstrapDialog.show({
        title: "Add Kinect Token",
        message: "You don't have much tokens in your wallet. please add more tokens in your wallet. <br/> <input type='number' class='form-control' id='token-input' min='1' required> <br> <span class='error' style='display: none;'>Atleast 1 token is required.</span>",
        closeByBackdrop: false,
        buttons: [{
            label: 'Add Tokens',
            action: function(dialog) {
              const kinectContractAbi = gon.contract_abi;
              const kinectContract = web3.eth.contract(kinectContractAbi);
              const kinectContractInstance = kinectContract.at(gon.contract_addresss);
              const account = web3.eth.accounts[0];
              const token = $('#token-input').val()
              if(parseInt(token) > 0) {
                $('.error').hide()
                $.ajax({
                  method: "POST",
                  url: "<%= add_tokens_users_path %>",
                  data: { walletAddress: account, token: parseInt(token) }
                }).done(function( data ) {
                  if($('.transaction-alert').hasClass('transaction-toggle')){
                    $('.transaction-alert').removeClass('transaction-toggle');
                  }
                });
                dialog.close();
              } else {
                $('.error').show()
              }
            }
        }, {
            label: 'Cancel',
            action: function(dialog) {
                dialog.close();
            }
        }]
      });
    }

    if (checkMetamaskWeb3()) {
      const kinectContractAbi = gon.contract_abi;
      const kinectContract = web3.eth.contract(kinectContractAbi);
      const kinectAddress = gon.contract_addresss;
      const kinectContractInstance = kinectContract.at(kinectAddress);
      const account = web3.eth.accounts[0];
      kinectContractInstance.balanceOf(account, (err, res2) => {
        let obj = err ? null : { balance: res2.toNumber() };
        let balance = obj.balance/1e18
        $('.balance').text(balance);
      });

      $('.token-patients').click(function(){
        kinectContractInstance.balanceOf(account, (err, res2) => {
          let obj = err ? null : { balance: res2.toNumber() };
          let no_tokens = $(this).attr("data-tokens");
          let no_patients = $(this).attr("data-patients")
          let balance = obj.balance/1e18
          if(parseInt(balance) >= parseInt(no_tokens)){
            $("#tokens-number")[0].value = no_tokens;
            $("#patients-number")[0].value = no_patients;
            $('#token-modal').modal('toggle');
          } else {
            purchaseDialog();
          }
        });
      })
      $('.purchase-submit').click(function(e){
        e.preventDefault();
        let available_patients = parseInt("<%= available_patients(@clinic) %>")
        let requested_patients = parseInt($("#patients-number").val())
        if(requested_patients <= available_patients){
          kinectContractInstance.balanceOf(account, (err, res2) => {
            let obj = err ? null : { balance: res2.toNumber() };
            let no_tokens = $("#tokens-number").val();
            let balance = obj.balance/1e18
            if(parseInt(balance) >= parseInt(no_tokens)){
              const kinectContractAbi = gon.contract_abi;
              const kinectContract = web3.eth.contract(kinectContractAbi);
              const kinectContractInstance = kinectContract.at(gon.contract_addresss);
              const account = web3.eth.accounts[0];
              const currentGasPrice = 1 * (10**9)
              kinectContractInstance.transfer(gon.contract_addresss, parseInt(no_tokens)*1e18, { from: account, gasPrice: web3.toHex(currentGasPrice) }, (err, res2) => {
                  if(!err){
                    $('#transaction_tx_hash').val(res2)
                    var form = $("#new_transaction")
                    var datastring = form.serialize();
                    var url = form[0].action.split("<%= root_url %>")[1]
                    $.ajax({
                      type: form[0].method,
                      url: "/"+url,
                      data: datastring,
                      success: function(data) {
                        $('#token-modal').modal('toggle');
                        if($('.p-transaction-alert').hasClass('p-transaction-toggle')){
                          $('.p-transaction-alert').removeClass('p-transaction-toggle');
                        }
                      }
                    });
                  } else {
                    $('#token-modal').modal('toggle');
                  }
              })
            } else {
              purchaseDialog();
              $('#token-modal').modal('toggle');
            }
          });
        } else {
          $('#token-modal').modal('toggle');
          toastr.warning("Requested no. of patients are not available");
        }
      })

      $('.add-tokens').on('click', function(){
        purchaseDialog();
      });
    }

    App.transactions = App.cable.subscriptions.create({
        channel: "TransactionsChannel",
        user_id: "<%= current_user.id %>"
      },
      {
        received: function(data) {
          let overview = data.overview
          if(typeof overview != 'undefined'){
            location.reload();
          }
          let transaction = data.transaction
          if(typeof transaction != 'undefined'){
            location.reload();
          }
        }
      }
    )
  })
</script>