config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  devise_for :users, :skip => [:registrations]

  as :user do
    get '/users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put '/users' => 'devise/registrations#update', :as => 'user_registration'
  end

  devise_for :patients, :skip => [:registrations], controllers: { sessions: 'patients/sessions' }

  as :patient do
    get "/patients/edit" => "devise/registrations#edit", :as => :edit_patient_registration
    put "/patients" => "devise/registrations#update", :as => :patient_registration
  end

  root to: 'dashboard#index'

  resources :dashboard, only: [:index] do
    collection do
      get 'states'
      post 'transaction_callback'
    end
  end

  resources :patients, except: :destroy do
    collection do
      post :send_otp
    end
    resources :consultations do
      resources :histories, only: [:create, :update]
      resources :treatments, only: [:create, :update]
      resources :examinations
      resources :diagnoses
      resources :general_notes
      resources :laboratory_requests, except:  :index
      resources :laboratory_results
      member do
        patch 'update_provider'
        patch 'update_disease'
      end
    end
  end

  resources :users, only: [] do
    collection do
      get 'user_balance'
      post 'add_tokens'
    end
    member do
      post 'send_reset_password_token'
    end
  end

  resources :clinics, only: [:index, :show] do
    member do
      get 'outcomes'
    end
    resources :transactions, only: [:create]
  end
  resources :transactions, only: [:index]

  get '/laboratory_patients', to: 'laboratory_requests#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :healthcare_professionals, except: [:show, :destroy]

  get '*path' => redirect('/')
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user_or_patient, except: :transaction_callback
  protect_from_forgery with: :null_session, only: :transaction_callback

  def index
    if current_user.aid?
      redirect_to clinics_path
    end
  end

  def states
    if params[:country].present?
      render json: { states: CS.states(params[:country]).sort }
    else
      render json: { states: [] }
    end
  end

  def transaction_callback
    if distribution_params[:overviewID].present?
      overview = DistributionOverview.find(distribution_params[:overviewID])
      overview.token = distribution_params[:token]
      overview.status = distribution_params[:status]
      overview.transaction_id = distribution_params[:transactionID]
      overview.transaction_type = distribution_params[:transactionType]
      overview.wallet_address = distribution_params[:walletAddress]
      if overview.save
        channel =
          if overview.user.present?
            "transactions_#{overview.user.id}_channel"
          elsif overview.patient.present?
            "transactions_#{overview.patient.id}_channel"
          end
        if channel.present?
          ActionCable.server.broadcast channel,
                                       overview: overview,
                                       user: overview.user,
                                       patient: overview.patient
          head :ok
        end
      end
    end
  end

  private

  def distribution_params
    params.require(:dashboard).permit(:key, :token, :status, :transactionID, :overviewID, :transactionType, :walletAddress)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<!-- Page Content Holder -->
<div id="content" class="dashboard-block">
  <%= render partial: '/shared/mobile_sidebar' %>

  <div class="heading">
    <h2>Dashboard</h2>
  </div>
  <div class="main-block">
    <div class="patient-blocks">
      <% unless current_user.clinic? %>
        <div class="col-md-4 col-sm-4 col-xs-12 resp-pad">
          <%= link_to (current_user.lab? ? laboratory_patients_path : patients_path) do %>
            <div class="existing-patient blocks">
              <span class="patient-icons">
                <%= image_tag 'existing-patient.png' %>
              </span>
              <span>Existing Patient <br> Consultation</span>
            </div>
          <% end %>
        </div>
      <% end %>
      <% if can? :create, Patient %>
        <div class="col-md-4 col-sm-4 col-xs-12 resp-pad">
          <%= link_to new_patient_path do %>
            <div class="new-patient blocks">
              <span class="patient-icons">
                <%= image_tag 'new-patient.png' %>
              </span>
              <span>New Patient <br> Consultation</span>
            </div>
          <% end %>
        </div>
      <% end %>
      <% if can? :manage, User %>
        <div class="col-md-4 col-sm-4 col-xs-12 resp-pad">
          <%= link_to healthcare_professionals_path do %>
            <div class="healthcare blocks">
              <span class="patient-icons">
                <%= image_tag 'healthcare.png' %>
              </span>
              <span>Healthcare <br> Professionals Listing</span>
            </div>
          <% end %>
        </div>
      <% end %>
      <% if can? :create, User %>
        <div class="col-md-4 col-sm-4 col-xs-12 resp-pad">
          <%= link_to new_healthcare_professional_path do %>
            <div class="healthcare blocks">
              <span class="patient-icons">
                <%= image_tag 'healthcare.png' %>
              </span>
              <span>Healthcare <br> Professionals Setup</span>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="clearfix"></div>
    <div class="dashboard-image">
      <%= image_tag 'dashboard.png' %>
    </div>
  </div>
</div>