config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  devise_for :users, :skip => [:registrations]

  as :user do
    get '/users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put '/users' => 'devise/registrations#update', :as => 'user_registration'
  end

  devise_for :patients, :skip => [:registrations], controllers: { sessions: 'patients/sessions' }

  as :patient do
    get "/patients/edit" => "devise/registrations#edit", :as => :edit_patient_registration
    put "/patients" => "devise/registrations#update", :as => :patient_registration
  end

  root to: 'dashboard#index'

  resources :dashboard, only: [:index] do
    collection do
      get 'states'
      post 'transaction_callback'
    end
  end

  resources :patients, except: :destroy do
    collection do
      post :send_otp
    end
    resources :consultations do
      resources :histories, only: [:create, :update]
      resources :treatments, only: [:create, :update]
      resources :examinations
      resources :diagnoses
      resources :general_notes
      resources :laboratory_requests, except:  :index
      resources :laboratory_results
      member do
        patch 'update_provider'
        patch 'update_disease'
      end
    end
  end

  resources :users, only: [] do
    collection do
      get 'user_balance'
      post 'add_tokens'
    end
    member do
      post 'send_reset_password_token'
    end
  end

  resources :clinics, only: [:index, :show] do
    member do
      get 'outcomes'
    end
    resources :transactions, only: [:create]
  end
  resources :transactions, only: [:index]

  get '/laboratory_patients', to: 'laboratory_requests#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :healthcare_professionals, except: [:show, :destroy]

  get '*path' => redirect('/')
end

app/views/layouts/shared/_flash_messages.html.erb
<script>
  $(document).ready(function(){
    "<% flash.each do |type, message| %>"
      "<% if type.eql?('notice') %>"
        toastr.success("<%= message %>");
      "<% end %>"
      "<% if type.eql?('alert') %>"
        toastr.warning("<%= message %>");
      "<% end %>"
    "<% end %>"

  });
</script>

app/views/layouts/shared/_header.html.erb
<header>
  <div class="logo col-md-3 col-sm-3">
    <%= link_to image_tag('logo.png'), current_user ? root_path : patient_path(current_patient) %>
  </div>
  <ul class="user-dropdown col-md-9 col-sm-9 pull-right text-right">
    <%# <li class="help">
      <a href="">Help <span class="glyphicon glyphicon-bell"></span></a>
    </li> %>
    <li class="dropdown">
      <a data-target="#" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-angle-down"></i>
        <% user = current_user || current_patient %>
        <%= user.fullname %>
      </a>

      <ul class="dropdown-menu logout-btn" aria-labelledby="dLabel">
        <li class="logout-li">
          <%= link_to('Change Password', current_patient.present? ? edit_patient_registration_path : edit_user_registration_path) %>
        </li>
        <li class="logout-li">
          <%= link_to('Logout', current_user.present? ? destroy_user_session_path : destroy_patient_session_path , method: :delete) %>
        </li>
      </ul>
    </li>
  </ul>
</header>

app/views/layouts/shared/_sidebar.html.erb
<!-- Sidebar Holder -->
<nav id="sidebar">
  <ul class="list-unstyled components">
    <% kinectnow = (controller_name == "transactions" && action_name == "index") %>
    <li class="<%= kinectnow ? 'active' : '' %>">
      <a href="#kinectnow" data-toggle="collapse" aria-expanded="<%= kinectnow %>">KinectNow</a>
      <ul class="collapse list-unstyled <%= kinectnow ? 'in' : '' %>" id="kinectnow">
        <li class="<%= kinectnow ? 'active' : '' %>">
          <%= link_to transactions_path do %>
            <span class="transaction-icon menu-icons"></span>
            <span class="menu-name">Transactions</span>
          <% end %>
        </li>
        <!--
          <li>
            <a href="javascript:void(0);">
              <span class="withdraw-icon menu-icons"></span>
              <span class="menu-name">Withdraw</span>
            </a>
          </li>
        -->
      </ul>
    </li>
    <% if current_user.aid? %>
      <li class="<%= @clinics || @patients ? 'active' : ''%>">
        <!-- <a href="/clinics" data-toggle="collapse" aria-expanded="true">KinectAID</a> -->
        <%= link_to "KinectAID", clinics_path %>
      </li>
    <% end %>

    <% if !current_user.aid? %>
      <% kinecthuman = (controller_name == "dashboard" && action_name == "index") %>
      <li class="<%= kinecthuman ? 'active' : ''%>">
        <a href="#kinecthuman" data-toggle="collapse" aria-expanded="<%= kinecthuman %>"> KinectHUMAN</a>
        <ul class="collapse list-unstyled <%= kinecthuman ? 'in' : '' %>" id="kinecthuman">
          <li class="<%= kinecthuman ? 'active' : '' %>">
            <%= link_to root_path do %>
              <span class="dashboard-icon menu-icons"></span>
              <span class="menu-name">Dashboard</span>
            <% end %>
          </li>
        </ul>
      </li>
    <% end %>
  </ul>
</nav>