config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  devise_for :users, :skip => [:registrations]

  as :user do
    get '/users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put '/users' => 'devise/registrations#update', :as => 'user_registration'
  end

  devise_for :patients, :skip => [:registrations], controllers: { sessions: 'patients/sessions' }

  as :patient do
    get "/patients/edit" => "devise/registrations#edit", :as => :edit_patient_registration
    put "/patients" => "devise/registrations#update", :as => :patient_registration
  end

  root to: 'dashboard#index'

  resources :dashboard, only: [:index] do
    collection do
      get 'states'
      post 'transaction_callback'
    end
  end

  resources :patients, except: :destroy do
    collection do
      post :send_otp
    end
    resources :consultations do
      resources :histories, only: [:create, :update]
      resources :treatments, only: [:create, :update]
      resources :examinations
      resources :diagnoses
      resources :general_notes
      resources :laboratory_requests, except:  :index
      resources :laboratory_results
      member do
        patch 'update_provider'
        patch 'update_disease'
      end
    end
  end

  resources :users, only: [] do
    collection do
      get 'user_balance'
      post 'add_tokens'
    end
    member do
      post 'send_reset_password_token'
    end
  end

  resources :clinics, only: [:index, :show] do
    member do
      get 'outcomes'
    end
    resources :transactions, only: [:create]
  end
  resources :transactions, only: [:index]

  get '/laboratory_patients', to: 'laboratory_requests#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :healthcare_professionals, except: [:show, :destroy]

  get '*path' => redirect('/')
end

app/controllers/healthcare_professionals_controller.rb
class HealthcareProfessionalsController < ApplicationController
  before_action :authenticate_user_or_patient
  before_action :find_healthcare_professional, only: [:edit, :update]

  def index
    @healthcare_professionals = current_user.healthcare_professionals.page(params[:page]).per(20)
  end

  def new
    @healthcare_professional = current_user.healthcare_professionals.new
    unless can? :create, @healthcare_professional
      redirect_to root_path, flash: { alert: t('denied_permission') }
    end
  end

  def create
    @healthcare_professional = current_user.healthcare_professionals.new(healthcare_professional_params)
    @healthcare_professional.password = SecureRandom.hex(10)
    if @healthcare_professional.save
      @healthcare_professional.add_role(params[:user][:roles])
      @healthcare_professional.send_reset_password_instructions
      redirect_to edit_healthcare_professional_path(@healthcare_professional), flash: { notice: 'Healthcare professional created!' }
    else
      render :new
    end
  end

  def edit
    @role = @healthcare_professional.roles.last.name
    unless can? :update, @healthcare_professional
      redirect_to root_path, flash: { alert: t('denied_permission') }
    end
  end

  def update
    if can? :update, @healthcare_professional
      if @healthcare_professional.update(healthcare_professional_params)
        @healthcare_professional.add_role(params[:user][:roles])
        redirect_to edit_healthcare_professional_path(@healthcare_professional), flash: { notice: 'Healthcare professional updated!' }
      else
        render :edit
      end
    else
      redirect_to root_path
    end
  end

  private

  def find_healthcare_professional
    @healthcare_professional = User.find_by(id: params[:id])
    redirect_to new_healthcare_professional_path, flash: { alert: 'No Healthcare Professional found' } unless @healthcare_professional
  end

  def healthcare_professional_params
    params.require(:user).permit(:uid, :fullname, :email, :address1, :suburb, :postal_code, :phone, :state, :country)
  end
end

app/helpers/healthcare_professionals_helper.rb
module HealthcareProfessionalsHelper
  def roles_list
    ['Clinician', 'Doctor', 'Nurse', 'Specialist']
  end
end

app/views/healthcare_professionals/edit.html.erb
<!-- Page Content Holder -->
<div id="content">
  <%= render partial: '/shared/mobile_sidebar' %>

  <div class="heading">
    <h2>Healthcare Professionals Maintenance</h2>
  </div>
    <div class="healthcare-form">
      <%= simple_form_for(@healthcare_professional, as: :user, method: :patch, url: healthcare_professional_path, html: { class: "form-horizontal form-row-seperated" }) do |f| %>
        <div class="form-group col-md-3 col-sm-3 col-xs-12 pad-left">
          <%= f.input :uid, :label => "ID", input_html: { class: "form-control", placeholder: "Enter ID" } %>
        </div>
        <div class="form-group col-md-3 col-sm-3 col-xs-12">
          <%= f.input :fullname, :label => "Full Name", input_html: { class: "form-control", placeholder: "Enter Fullname" } %>
        </div>
        <div class="form-group col-md-3 col-sm-3 col-xs-12">
          <%= f.input :email, :label => "Email", input_html: { class: "form-control", placeholder: "Enter Email Address" } %>
        </div>
        <div class="form-group col-md-3 col-sm-3 col-xs-12">
          <%= f.input :roles,:collection => roles_list, :include_blank => true, :label => "Role", input_html: { class: "form-control" } %>
        </div>
        <div class="form-group col-md-12 col-sm-12 col-xs-12 pad-left">
          <%= f.input :address1, as: :text, label: 'Address', input_html: { class: "form-control", placeholder: "Enter address" } %>
        </div>
        <div class="form-group col-md-4 col-sm-4 col-xs-12 pad-left">
          <%= f.input :suburb, :label => "Suburb", input_html: { class: "form-control", placeholder: "Enter suburb" } %>
        </div>

        <div class="form-group col-md-4 col-sm-4 col-xs-12">
          <%= f.label :country %>
          <%= f.input :country, collection: CS.countries.sort.collect { |x| [x[1], x[0]] }, prompt: "Select Country", label: false, input_html: { class: 'form-control' } %>
        </div>
        <div class="form-group col-md-4 col-sm-4 col-xs-12">
          <%= f.label :state %>
          <%= f.input :state, collection: [], prompt: "Select State", label: false, input_html: { class: "form-control" } %>
        </div>

        <div class="form-group col-md-4 col-sm-4 col-xs-12 pad-left">
          <%= f.input :postal_code, label: "Postcode", input_html: { class: "form-control", placeholder: "Enter postcode" } %>
        </div>
        <div class="form-group col-md-4 col-sm-4 col-xs-12">
          <%= f.input :phonenumber, input_html: { class: "form-control", placeholder: "Enter phone number" } %>
          <%= f.input :phone, as: :hidden %>
        </div>
        <div class="clearfix"></div>
        <%= f.submit "Update", class: "btn save-btn" %>
      <% end %>
    </div> <!-- healthcare-form -->
</div> <!-- content -->

<script>
$(document).on("turbolinks:load", function(){
  $('#user_country').on('change', function(){
    var country = $(this).val();
    $.get( "<%= states_dashboard_index_path %>", { country: country } )
    .done(function( data ) {
      if(data.states.length > 0){
        var state_select = $("#user_state").html("");
        data.states.forEach(function(value, index){
          state_select.append("<option value='"+value[0]+"'>"+value[1]+"</option>")
        })
        state_select.val("<%= @healthcare_professional.state %>");
      }
    });
  });

  $("#edit_user").validate({
    rules: {
      "user[roles]": { required: true },
      "user[phonenumber]": {
        required: true,
        // phoneUS: true
      }
    },
    errorPlacement: function(error, element) {
      if (element.parent().parent().hasClass('radio_buttons')){
          element = element.parent().parent();
      }
      error.insertAfter(element);
    }
  });

  $('#user_country').change();

  $('#user_roles').val("<%= @role %>");

  $('#user_phonenumber').intlTelInput({
    initialCountry: "auto",
    formatOnInit: true,
    separateDialCode: true,
    utilsScript: "assets/libphonenumber/utils.js",
    geoIpLookup: function(callback) {
      $.get("https://ipinfo.io", function() {}, "jsonp").always(function(resp) {
        var countryCode = (resp && resp.country) ? resp.country : "";
        callback(countryCode);
      });
    }
  });

  $('#user_phonenumber').on('change', function(){
    $('#user_phone').val($('#user_phonenumber').intlTelInput("getNumber"));
  })

  if("<%= @healthcare_professional.phone.present? %>" == "true"){
    $("#user_phonenumber").intlTelInput("setNumber", "<%= @healthcare_professional.phone %>");
  }
})
</script>

app/views/healthcare_professionals/index.html.erb
<div id="content" class="exist-block">
  <%= render partial: '/shared/mobile_sidebar' %>

  <div class="heading">
    <h2>Healthcare Professionals</h2>
  </div>

  <div class="existing-table">
     <table class="table table-hover footable">
      <thead>
        <tr>
          <th>ID </th>
          <th>Name</th>
          <th data-hide="phone">Email</th>
          <th data-hide="phone">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @healthcare_professionals.each do |healthcare| %>
          <tr>
            <td><%= healthcare.uid %></td>
            <td><%= healthcare.fullname %></td>
            <td><%= healthcare.email %></td>
            <td><%= link_to "EDIT", edit_healthcare_professional_path(healthcare.id), class: "btn btn-default" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div> <!-- existing table -->
  <%= paginate @healthcare_professionals %>
</div>

<script type="text/javascript">
  $('.footable').footable({
    calculateWidthOverride: function() {
      return { width: $(window).width() };
    }
  });
</script>

app/views/healthcare_professionals/new.html.erb
<!-- Page Content Holder -->
<div id="content">
  <%= render partial: '/shared/mobile_sidebar' %>

  <div class="heading profession">
    <h2>Healthcare Professionals Maintenance</h2>
  </div>
  <div class="healthcare-form">
    <%= simple_form_for(@healthcare_professional, as: :user, method: :post, url: healthcare_professionals_path, html: { class: "form-horizontal form-row-seperated" }) do |f| %>
      <div class="row row-margin">
        <div class="form-group col-md-3 col-sm-3 col-xs-12 pad-left">
          <%= f.input :uid, :label => "ID", input_html: { class: "form-control", placeholder: "Enter ID" } %>
        </div>
        <div class="form-group col-md-3 col-sm-3 col-xs-12">
          <%= f.input :fullname, :label => "Full Name", input_html: { class: "form-control", placeholder: "Enter Fullname" } %>
        </div>
        <div class="form-group col-md-3 col-sm-3 col-xs-12">
          <%= f.input :email, :label => "Email", input_html: { class: "form-control", placeholder: "Enter Email Address" } %>
        </div>
        <div class="form-group col-md-3 col-sm-3 col-xs-12">
          <%= f.label :roles, "Role" %>
          <%= f.input :roles,:collection => roles_list, prompt: "Select role", label: false, input_html: { class: "form-control" } %>
        </div>
      </div>
      <div class="row row-margin">
        <div class="form-group col-md-12 col-sm-12 col-xs-12 pad-left">
          <%= f.input :address1, as: :text, label: 'Address', input_html: { class: "form-control", placeholder: "Enter address" } %>
        </div>
      </div>
      <div class="row row-margin">
        <div class="form-group col-md-4 col-sm-4 col-xs-12 pad-left">
          <%= f.input :suburb, :label => "Suburb", input_html: { class: "form-control", placeholder: "Enter suburb" } %>
        </div>
        <div class="form-group col-md-4 col-sm-4 col-xs-12">
          <%= f.label :country %>
          <%= f.input :country, collection: CS.countries.sort.collect { |x| [x[1], x[0]] }, prompt: "Select Country", label: false, input_html: { class: 'form-control' } %>
        </div>
        <div class="form-group col-md-4 col-sm-4 col-xs-12">
          <%= f.label :state %>
          <%= f.input :state, collection: [], prompt: "Select State", label: false, input_html: { class: "form-control" } %>
        </div>
      </div>
      <div class="row row-margin">
        <div class="form-group col-md-4 col-sm-4 col-xs-12 pad-left">
          <%= f.input :postal_code, label: "Postcode", input_html: { class: "form-control", placeholder: "Enter postcode" } %>
        </div>
        <div class="form-group col-md-4 col-sm-4 col-xs-12">
          <%= f.input :phonenumber, input_html: { class: "form-control", placeholder: "Enter phone number" } %>
          <%= f.input :phone, as: :hidden %>
        </div>
      </div>
      <div class="clearfix"></div>
      <div class="save-button">
        <%= f.submit "Save New", class: "btn save-btn" %>
      </div>
    <% end %>
  </div> <!-- healthcare-form -->
</div> <!-- content -->

<script>
  $(document).on("turbolinks:load", function(){
    $("#user_roles").val('');
    $("#user_phonenumber").val('');

    $('#user_country').on('change', function(){
      var country = $(this).val();
      $.get( "<%= states_dashboard_index_path %>", { country: country } )
      .done(function( data ) {
        if(data.states.length > 0){
          var state_select = $("#user_state").html("");
          data.states.forEach(function(value, index){
            state_select.append("<option value='"+value[0]+"'>"+value[1]+"</option>")
          })
        }
      });
    });

    $("#new_user").validate({
      rules: {
        "user[roles]": { required: true },
        "user[phonenumber]": { required: true },
        required: true,
        // phoneUS: true
      },
      errorPlacement: function(error, element) {
        if (element.parent().parent().hasClass('radio_buttons')){
            element = element.parent().parent();
        }
        error.insertAfter(element);
      }
    });

    $('#user_phonenumber').intlTelInput({
      initialCountry: "auto",
      formatOnInit: true,
      separateDialCode: true,
      utilsScript: "assets/libphonenumber/utils.js",
      geoIpLookup: function(callback) {
        $.get("https://ipinfo.io", function() {}, "jsonp").always(function(resp) {
          var countryCode = (resp && resp.country) ? resp.country : "";
          callback(countryCode);
        });
      }
    });

    $('#user_phonenumber').on('change', function(){
      $('#user_phone').val($('#user_phonenumber').intlTelInput("getNumber"));
    })
  })
</script>